version: '3.6'

services:
  api-gateway:
    build: ./ApiGateway
    ports:
      - "8080:8080"
    depends_on:
      - redis_db
      - db
    networks:
      - cryptos
  customers:
    build: ./Customers
    ports:
      - "9090:8080"
    depends_on:
      - db
    networks:
      - cryptos
  payments:
    build: ./Payment
    ports:
      - "8081:8080"
    environment:
      API_KEY: sk_test_51MH0dvCucZ6lucMqNVBvffVtbqwA8kucCFkzmNS421Q7nEGu05Xnn3CM5ChaaDBJO65FhdgQQJnFMmpeNZRXgAV600Ocp05xfs
    depends_on:
      - db
    networks:
      - cryptos
  trading:
    build: ./Trading
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - cryptos
  market-data:
    build: ./MarketData
    ports:
      - "8083:8080"
    depends_on:
      - db
    networks:
      - cryptos
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cryptos
  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - cryptos
networks:
  cryptos:
