spring:
  application:
    name: payments
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3306/payments
    username: root
    password: root
    hikari:
      maximum-pool-size: 32
      minimum-idle: 10
      connection-timeout: 60000

customers:
  get-customer-by-id-url: http://Customers:8080/private/customers/data/{customerId}
currency-conversion:
  exchange-rates-url: https://v6.exchangerate-api.com/v6/6385298c43a888c7956e7680/latest/{fromCurrency}